### ISSUE TITLE
When used in VSTO addIn browser is never created (EBWebView permissions)

### ISSUE THREAD

**Issue by raix** [MicrosoftEdge/WebViewFeedback#102]
I've created a small sample project using the WebView2 in a VSTO addIn but it's not creating the browser.

I'm using:
```xml
  <package id="Microsoft.Web.WebView2" version="0.8.355" targetFramework="net461" />
  <package id="MtrDev.WebView2.Interop" version="0.8.355.3" targetFramework="net461" />
  <package id="MtrDev.WebView2.WinForms" version="0.8.355.2" targetFramework="net461" />
```

On BeforeEnvironmentCreated BrowserExecutableFolder/BrowserArguments/UserDataFolder are all null.

On environment created I get the BrowserVersionInfo "81.0.389.2 dev"

BrowserCreated never gets called.

--

When I create the `C:\Program Files\Microsoft Office\root\Office16\powerpnt.exe.WebView2\EBWebView` folder and grant access it starts working!

I'm guessing the path is configured on environment create (before environment create it's null)

Is it intentionally that the folder is needed / in the right location?

Kind regards Morten

**Comment by michael-russin** [comment]
Since you question is related to the wrapper I wrote I copied you question to the [WebView2 control project](https://github.com/michael-russin/webview2-control/issues/3) and answered it there.   The underlying issue is you'll need to change the cache directory for WebView2 to a folder the user has write access to.

**Comment by raix** [comment]
Thanks @michael-russin - it might be related to the wrapper not throwing an exception on permission issues.

It would be nice with a good default user data folder when running in the vsto. (or an exception)

**Comment by pagoe-msft** [comment]
Hi raix,

Closing this issue for now as it seems to relate to the WebVIew2 control project. 

On our end, we are actively working on our own WinForms wrapper which we will release soon. I'll circle back to this thread when we release it.

**Comment by raix** [comment]
@pagoe-msft sounds good, very much looking forward to it :) - will it work with the public version of the new edge released yesterday - or will it require 80.x?

**Comment by pagoe-msft** [comment]
Hi raix,

Our .NET wrapper will work with the version of Edge that our SDK supports at that time. Since our .NET wrapper won't be available for a few months, it won't work with the version of Edge that was released yesterday. It will work with the Canary version of Edge at the time of release. 

We will make sure to do a better job documenting and providing more clarity when we release the .NET preview. 

Thanks for the feedback!
