### ISSUE TITLE
Stable Edge Release issues with WebView2

### ISSUE THREAD

**Issue by cengman7** [MicrosoftEdge/WebViewFeedback#103]
I've been developing with the beta Edge and c++.  Things were going well.

Yesterday I installed the release version of Edge and it won't load that version. I get:
Loader skipped an incompatible version: C:\Program Files (x86)\Microsoft\Edge\Application\79.0.309.65

Why won't it load WebView2 with the actual release version of Edge? 

I'm sure I'm just doing something stupid (or not doing something obvious).

BTW, I'm using CreateWebView2Environment().

**Comment by pagoe-msft** [comment]
Hey cengman7,

Not a stupid question at all!

Currently, WebView2 is under developer preview. For every preview release, we're requiring the latest *Canary* at the time of the release so that developers have access to the latest changes we're making  for prototyping/testing, instead of waiting weeks for the change to land in Stable.

When we exit the preview status and make our V1 release, we will make sure new SDK releases work with the latest Stable at the time of release. For now, please use the compat info in release notes to determine browser compatibility: https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes

The 0.8.270 version is the latest version of our NuGet package that should work with the stable release.
https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes#08270

**Comment by cengman7** [comment]
Thank you.  Is there a target date for V2 WebView2 release?

**Comment by ukandrewc** [comment]
Would you be able to give some idea of wehn we can see the first Webview2 control for Winforms?
It would be a great help to my current planning if you could.
Thanks

**Comment by pagoe-msft** [comment]
Yes, we are currently targeting a release of our WinForms preview by the end of March

**Comment by ukandrewc** [comment]
Great, thank you.

**Comment by fvanheeswijk** [comment]
Is there a new target date available?

**Comment by mainseq** [comment]
The current demo of webview2 is still broken. After updating the Webview2 NuGet package it no longer can reference two "experimental" classes... The winform version would be more useful so those in VB.NET and C# can use it without win32 SetParent or similar hack...

**Comment by pagoe-msft** [comment]
@fvanheeswijk  Apologies, we had a few issues come up that have caused us to delay the launch of our .NET preview. We are working very hard and should have a release soon! I'll ping this thread when we release the .NET preview.

**Comment by mainseq** [comment]
I have a couple of questions:

1) will window.open work like it did in the old webview or do we have to rely on the event? Relying on the event breaks many oAuth and similar existing applications. Also it would be nice to get the default right-click context menu back unless you disable it via property... it is difficult or impossible to recreate all of the options manually.

2) Will JavaScript alerts and confirms work natively? These also broke many sites because they are synchronous calls and cannot use an event. 

Thanks...

**Comment by david-risney** [comment]
1. With [NewWindowRequested event](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/icorewebview2#add_newwindowrequested) by default on desktop WebView2 will just open a new window. You can use the event to instead provide your own new WebView2 that should act as the new window or you can cancel the window.open in the event.
2. By default alert, confirm, and prompt will all work like they do in the browser. You can use the [ScriptDialogOpening event](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/icorewebview2#add_scriptdialogopening) to suppress them or replace the dialog with your own dialog.
