### ISSUE TITLE
Display XML files with Edge (including XSLs)

### ISSUE THREAD

**Issue by MarkusSchreiner** [MicrosoftEdge/WebViewFeedback#145]
In our application I have to let the user view XML files (via the embedded Edge Browser).

Question 1: Does Edge currently support the display of XML files? I am only ever shown a blank page when loading a XML file (either with or without XSL).
Question 2: Are XML embedded XSL files loaded? The WebResourceRequested-Callback will not be executed for the corresponding XSL. (initialized with AddWebResourceRequestedFilter(L "*", CORE_WEBVIEW2_WEB_RESOURCE_CONTEXT_ALL))

Here are two sample files (XML & XSL), which are displayed correctly e.g. in Internet Explorer, but only an empty page is visible in Edge. Not even the context menu via right click works.

----XML---- (example.xml):

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="example.xsl" ?>
<breakfast_menu>
  <food>
    <name>Belgian Waffles</name>
    <price>$5.95</price>
    <description>Two of our famous Belgian Waffles with plenty of real maple syrup</description>
    <calories>650</calories>
  </food>
  <food>
    <name>Strawberry Belgian Waffles</name>
    <price>$7.95</price>
    <description>Light Belgian waffles covered with strawberries and whipped cream</description>
    <calories>900</calories>
  </food>
  <food>
    <name>Berry-Berry Belgian Waffles</name>
    <price>$8.95</price>
    <description>Light Belgian waffles covered with an assortment of fresh berries and whipped cream</description>
    <calories>900</calories>
  </food>
</breakfast_menu>
```

----XSL---- (example.xsl):

```
<?xml version="1.0" encoding="UTF-8"?>
<html xsl:version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<body style="font-family:Arial;font-size:12pt;background-color:#EEEEEE">
<xsl:for-each select="breakfast_menu/food">
  <div style="background-color:teal;color:white;padding:4px">
    <span style="font-weight:bold"><xsl:value-of select="name"/> - </span>
    <xsl:value-of select="price"/>
  </div>
  <div style="margin-left:20px;margin-bottom:1em;font-size:10pt">
    <p>
      <xsl:value-of select="description"/>
      <span style="font-style:italic"> (<xsl:value-of select="calories"/> calories per serving)</span>
    </p>
  </div>
</xsl:for-each>
</body>
</html>
```

**Comment by david-risney** [comment]
WebView2 should match Edge and in turn Edge should match Chromium behavior in terms of XML/XSLT support. You might try getting it working in the browser first. I saw [this on stackoverflow](https://stackoverflow.com/a/2981917) which suggests that XML/XSLT served from file: URIs isn't allowed due to security issues.

**Comment by MarkusSchreiner** [comment]
Thank you. That was a good clue!
When I start Edge with the parameter `--allow-file-access-from-files`, XML/XSL files are displayed properly.

**Comment by ajtruckle** [comment]
> WebView2 should match Edge and in turn Edge should match Chromium behavior in terms of XML/XSLT support. You might try getting it working in the browser first. I saw [this on stackoverflow](https://stackoverflow.com/a/2981917) which suggests that XML/XSLT served from file: URIs isn't allowed due to security issues.

At the moment I use CHtmlView in my MFC application and it is the core of the software,. It uses XML / XSL to display the schedule to the user. This schedule is on their PC so it is a local file. When I try the sample Win32 API build it displays nothing when I navigate to the XML file.

Microsoft want us to use WebView2. They are ditching IE in Windows 11. Yet by design WebView2 will not show a standard PrintPreview without using Javascript workaround. And now, based on your comment, it will now display XML/XSL transforms local to PC. In short, WebView2 as an alternative has crippled my software. Is there going to be a solution to these issues? CHtmlView was simple from my perspective to use and was rich in features as is. Thanks.

**Comment by ajtruckle** [comment]
At the time I did get it working too:

```
void CWebBrowser::InitializeWebView()
{
   CloseWebView();

   CString subFolder = GetInstallPath();
   CString appData = GetUserDataFolder();
   /* ICoreWebView2EnvironmentOptions* options = nullptr; */

   auto options = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
   CHECK_FAILURE(options->put_AdditionalBrowserArguments(L"--allow-file-access-from-files"));

   HRESULT hr = CreateCoreWebView2EnvironmentWithOptions(
	   subFolder,
	   appData,
	   options.Get(),
	   Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
		   this,
		   &CWebBrowser::OnCreateEnvironmentCompleted).Get());

   if (!SUCCEEDED(hr))
   {
      CString text;
      if (hr == HRESULT_FROM_WIN32(ERROR_FILE_NOT_FOUND))
      {
         text = L"Cannot found the WebView2 component.";
      }
      else
      {
         text = L"Cannot create the webview environment.";
      }

      ShowFailure(hr, text);
   }
}
```
It does indeed work which is fab. But I had too many things not implemented in the viewer and suspended development.
