### ISSUE TITLE
WebView2 Availability for Commercial Edge Chromium

### ISSUE THREAD

**Issue by brianclink** [MicrosoftEdge/WebViewFeedback#146]
We've committed to using Edge-Chromium and the new WebView2 control.
Any update on the when it will become generally available? (Currently it is "developer preview").

**Comment by liminzhu** [comment]
Fair question @brianclink . We are discussing timelines internally and once we have some clarity I will share here.

**Comment by brianclink** [comment]
Webview2 is in pre-release, can we ship and sell applications using this technology now?

**Comment by liminzhu** [comment]
Some updates @brianclink - we're targeting Q4 2020 for GA, see [roadmap](https://docs.microsoft.com/en-us/microsoft-edge/webview2/roadmap).

I'd advise against shipping WebView2 in production apps before we GA. A couple reasons, 
1. There are changes underway for our [distribution model](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#roadmap). We are making a WebView2 Runtime (with its own installer) instead of using Edge Stable as the underlying web platform that webview2 targets. They are almost the same, except WebView2 Runtime won't show up on users machine as the Edge browser. The in-development WebView2 Runtime is is what apps should use for production.
2. Prior to GA, we do not offer any backwards compat promises on our SDK. You can run into a situation where a browser/WebView Runtime update breaks the SDK.
