### ISSUE TITLE
Crash using GetCoreWebView2BrowserVersionInfo on Server 2012 R2

### ISSUE THREAD

**Issue by liminzhu** [MicrosoftEdge/WebViewFeedback#150]
// Copied from @KeesvanHeerden from https://github.com/MicrosoftDocs/edge-developer/issues/558

Before creating a webview2 environment (CreateCoreWebView2EnvironmentWithDetails), I check if the Edge version is suitable via the GetCoreWebView2BrowserVersionInfo and CompareBrowserVersions functions.

Using these functions on a server with Windows Server 2012 R2, it crashes on the function GetCoreWebView2BrowserVersionInfo. I know that Webview2 is yet not supported on that server version, but I expected the method to return a not S_OK value, or an emtpy string with version info. Not a crash.

I hope this can be changed, that a function will be added to check if the windows version is supported, because it is still not clear yet which windows versions will be supported in the future.
Thanks for reading.

**Comment by liminzhu** [comment]
Thanks for reporting the issue @KeesvanHeerden, this is our main feedback repo for WebView2 so i'm copying your issue on the docs repo to here :). 

That said, we did declare Server support with the [0.9.430 SDK release](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes#09430), so it's something we'd want to look into. 

To help us find the issue, what channels of Edge (Canary, Dev, etc.) do you have on Server and what version are they on?

**Comment by KeesvanHeerden** [comment]
The crash doesn’t depend on the Edge channel and version. The crash also happens on for example Windows Server 2008, Windows Server 2008 R2 and Windows Server 2012.
In some cases there was even no Edge available.
The thing is, that our application with the embedded Edge, can be used on many different environments. For now we use Internet Explorer as embedded browser.
I choose to test if we can use Edge as embedded browser via the GetCoreWebView2BrowserVersionInfo, because it seems the best way. I think that GetCoreWebView2BrowserVersionInfo should not crash, even if there is no Edge available.
My english is not very good, so I hope I explained it well enough.

Best regards,

[cid:image001.png@01D608C9.82D53D70]
Kees van Heerden
Senior Software Engineer

Tangram BV
De Bouw 149
3991 SZ HOUTEN

T  +31 30 6919171
E  kvanheerden@tangram.nl<mailto:kvanheerden@tangram.nl>

www.tangram.nl<https://www.tangram.nl/>

[https://www.tangram-tis.nl/custom/common/linkedin-outlook.gif]<https://www.linkedin.com/company/tangram/>




Van: Limin Zhu <notifications@github.com>
Verzonden: woensdag 1 april 2020 19:59
Aan: MicrosoftEdge/WebViewFeedback <WebViewFeedback@noreply.github.com>
CC: Kees van Heerden <KvanHeerden@tangram.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [MicrosoftEdge/WebViewFeedback] Crash using GetCoreWebView2BrowserVersionInfo on Server 2012 R2 (#150)


Thanks for reporting the issue @KeesvanHeerden<https://github.com/KeesvanHeerden>, this is our main feedback repo for WebView2 so i'm copying your issue on the docs repo to here :).

That said, we did declare Server support with the 0.9.430 SDK release<https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes#09430>, so it's something we'd want to look into.

To help us find the issue, what channels of Edge (Canary, Dev, etc.) do you have on Server and what version are they on?

**Comment by champnic** [comment]
@KeesvanHeerden We were unable to reproduce this issue on Server 2012 R2, using SDK 0.9.430+. If you are still seeing this, please reopen this issue and we'll take another look. Thanks!
