### ISSUE TITLE
Example ExecuteScriptAsync

### ISSUE THREAD

**Issue by iriarteburundarena** [MicrosoftEdge/WebViewFeedback#180]
I have the following example:

var val = webView.CoreWebView2.ExecuteScriptAsync("document.getElementById('id').value;");
string str_result = val.Result;

I can't get anything in the "Result" property, could someone give me a basic example of how to get a DOM value using ExecuteScriptAsync.

Thanks in advance!!

**Comment by ukandrewc** [comment]
It's because it's an Async function, you need to use await.

`var val = await webView.CoreWebView2.ExecuteScriptAsync("document.getElementById('id').value;");`

or handle the task return yourself, e.g.
```
{
    var Execute = "";
    var Task = TopBrowser.ExecuteScriptAsync(Script);
    Task.ContinueWith(() =>
    {
        if (!Task.IsFaulted)
        {
            Execute = Task.Result;
        }
        Frame.Continue = false;
    });
    Frame.Continue = true;
    Dispatcher.PushFrame(Frame);
}
```
If you need a .Net DOM, then [this project may help](https://github.com/ukandrewc/Webview2.Winforms.DOM)

**Comment by iriarteburundarena** [comment]
It works!!

Thanks a lot!!
