### ISSUE TITLE
CoreWebView2.CapturePreviewAsync has no callback handler in C#

### ISSUE THREAD

**Issue by jameslin0312** [MicrosoftEdge/WebViewFeedback#192]
In C#, CoreWebView2.CapturePreviewAsync has no callback handler parameter to be invoked when CapturePreview finishes writing to the stream. Also, If I call Wait on the return Task, the process will be stuck.

**Comment by david-risney** [comment]
CapturePreviewAsync returns a Task that should complete when done writing to the provided stream. Do you find that's not happening?

Does Task.Wait wait without pumping messages? The WebView2 APIs need to be called on the UI thread on which the WebView2 was created and all callbacks come back to that thread as well. If you do some kind of wait that isn't pumping messages then the completion callback message won't be able to get through in order to complete the CapturePreviewAsync call.

**Comment by jameslin0312** [comment]
Thanks a lot for your help! I can use await to solve my problem.
