### ISSUE TITLE
Navigation Events not in WebView2() Class

### ISSUE THREAD

**Issue by mikemeinz** [MicrosoftEdge/WebViewFeedback#214]
I have a working WebView application. I am starting to work on converting it to use WebView2. 

There are several events thrown by the WebView control that are not thrown by the WebView2 control. My application depends on the first two of those listed below. The others are nice to have. Will these events be available in the WebView control?

- DOMContentLoaded *
- FrameNavigationStarting *
- FrameContentLoading
- FrameDOMContentLoaded
- FrameNavigationCompleted

**Comment by david-risney** [comment]
The WebView2 control has APIs only for the most popular functionality. Otherwise it exposes a CoreWebView2 property that has more APIs [including FrameNavigationStarting](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-515/microsoft-web-webview2-core-corewebview2#framenavigationstarting) and FrameNavigationCompleted.

But no we don't have Frame/DOMContentLoaded or FrameContentLoading. Can you describe how you use these events or elaborate more on your app? Thanks!

**Comment by ukandrewc** [comment]
You can get these by adding scripting and calling .Net from there e.g.

`addEventListener("DOMContentLoaded", raiseMyContentLoading, { 'once': true })`

**Comment by mikemeinz** [comment]
At your suggestion, I have used the CoreWebView2 **FrameNavigationStarting** and **FrameNavigationCompleted** events. With these events and the "ContentLoading" event, I have been able to get the functionality that I require. You can close this issue if you wish..  

I needed a way to determine that the loading of an iframe from a third-party was not successful and I needed a way to tell when to close the WebView2 window. I count **FrameNavigationStarting** and **FrameNavigationCompleted** events. If I don't get the correct number within four seconds, I reset and start over. This rarely occurs and resetting and restarting usually solves it. To signal the program to close the WebView2 window, I use JavaScript code to cause a second **ContentLoading** event.  This is the JavaScript that I use:  `window.location="about:blank"; ` When the second **ContentLoading** event occurrs, the window closes immediately.

**Comment by david-risney** [comment]
Thanks!
