### ISSUE TITLE
Support #import "WebView2.tlb"

### ISSUE THREAD

**Issue by rtanabe999** [MicrosoftEdge/WebViewFeedback#22]
Because, auto define useful smart pointer and interface

**Comment by liminzhu** [comment]
@david-risney

**Comment by david-risney** [comment]
Good suggestion. What language and UI framework are you planning to use WebView2 in? Do you want the TLB to generate an assembly for using WebView2 in C#?

**Comment by rtanabe999** [comment]
In C++ and WTL, not C#

**Comment by liminzhu** [comment]
Hey @rtanabe999, we've included the tlb file in our latest release, let us know if you have any further questions/requests!

**Comment by rtanabe999** [comment]
Confirmed that the problem was solved.
Thank you !

**Comment by xiaoyaocode163** [comment]
> Hey @rtanabe999, we've included the tlb file in our latest release, let us know if you have any further questions/requests!
> 
> https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes#08230

I searched Bing and Google Search Engine, but I couldn't find WebView2.tlb, and I didn't install vs2019. I don't know if this TLB can be directly supported by VisualBasic 6.0. Can I directly add controls instead of Webbrowser?
I spent a few hours writing for help and researched some of the same type of COM wrapper and chromium wrapper.

**Comment by david-risney** [comment]
We have a TLB file in the nuget package, but we don't have an ActiveX control.
