### ISSUE TITLE
Null Reference Exception on start up

### ISSUE THREAD

**Issue by dan-toadllc** [MicrosoftEdge/WebViewFeedback#263]
I'm getting a NullReferenceException error on this line in Form1.Designer.cs:

 this.Controls.Add(this.webView21);

I don't see anything that is null.

[AB#26932580](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/26932580)

**Comment by mikemeinz** [comment]
@dan-toadllc

I had problem similar (if not the same) as yours. It turned out that the directives in the NuGet package don't specify that the the **WebView2Loader.dll** should be included. Maybe my solution will help you.

I modified the two Microsoft.Web.WebView2.targets files in the NuGet package so that the ClickOnce (Publish) feature of Visual Studio would copy the WebView2Loader.dll to the AppPublish directory. I changed **None** to **Content** and **Include** to **Included**. This has been reported as a bug in [Issue 228](https://github.com/MicrosoftEdge/WebViewFeedback/issues/228).

Before
```
<ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)$(EffectivePlatform)\WebView2Loader.dll">
      <Link>%(Filename)%(Extension)</Link>
      <PublishState>Include</PublishState>
      <Visible>False</Visible>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

```
After
```
  <ItemGroup>
    <Content Include="$(MSBuildThisFileDirectory)$(EffectivePlatform)\WebView2Loader.dll">
      <Link>%(Filename)%(Extension)</Link>
      <PublishState>Included</PublishState>
      <Visible>False</Visible>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

```

**Comment by champnic** [comment]
@dan-toadllc Could you try @mikemeinz change above and see if that fixes it? If so, we'll fix this as part of #228.

**Comment by champnic** [comment]
@dan-toadllc We haven't heard back in a month so I'm closing this for now. If you are still running into this issue please reactivate and we'll take another look. Thanks!

**Comment by alexbitsnz** [comment]
This is definitely an issue.  I am not sure where you make the changes you have suggested mikemeinz....

**Comment by mikemeinz** [comment]
@alexbitsnz 

On my PC, there are two files named **Microsoft.Web.WebView2.targets**. One of them is in **C:\Users\<USERNAME>\.nuget\packages\microsoft.web.webview2\0.9.538-prerelease\build\native**. The other file is in **C:\Users\<USERNAME>\.nuget\packages\microsoft.web.webview2\0.9.538-prerelease\build.** I used Windows Explorer Search to find them.

I made the same edit in both files. See Jun 12 post above.

**Comment by alexbitsnz** [comment]
Thank you Mike, that helped a lot :-)

**Comment by champnic** [comment]
@alexbitsnz Glad @mikemeinz 's fix helped. We're tracking that issue in #228.
