### ISSUE TITLE
Could not install .Net WinForms 'Microsoft.Web.WebView2 0.8.190'

### ISSUE THREAD

**Issue by TriSysBusinessSoftware** [MicrosoftEdge/WebViewFeedback#32]
I created a .Net WinForms project is VS2017 and attempted to install Microsoft.Web.WebView2 but received an error:

![webview-2-fail](https://user-images.githubusercontent.com/5684253/61518824-6739ab80-aa02-11e9-9257-aad28993065a.png)

Could not install package 'Microsoft.Web.WebView2 0.8.190'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by david-risney** [comment]
We don't yet directly support integration with WinForms or .NET. If you want to try it in .NET you'd need to pinvoke. Although I'm surprised that you're unable to add the package in order to then create pinvokes.

I've marked this feature request for the .NET / WinForms support, and bug for not being able to install the package to even attempt to add pinvokes.

**Comment by liminzhu** [comment]
Hey @TriSysBusinessSoftware we've fixed the issue in the latest [release](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes#08230), now you can install the package in .net projects. Let us know if you have more questions/requests!
