### ISSUE TITLE
Activex/Com support for using in VFP/VB/VBA

### ISSUE THREAD

**Issue by anilgenius** [MicrosoftEdge/WebViewFeedback#321]
I wish if webview2 will work as com component so vfp/vb developers can use the power of real html5 in their applications.

Regards
Anil

[AB#27454614](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27454614)

**Comment by pagoe-msft** [comment]
@anilgenius 

Thanks for the feedback, I've created a feature request! I'll come back to this thread if we have updates/more questions.

**Comment by liminzhu** [comment]
Thanks for the feedback @anilgenius . I have to be open and set expectations - we've looked at the item, and because of how outdated Active and Active Containers are as technology, we don't have any plans to support this in the near future. 

Closing the issue for now. If there are others asking for this, we can re-open/revisit.

**Comment by mlnikfreak** [comment]
Really no chances of seeing support in MS Access / VBA ?

**Comment by champnic** [comment]
Hey @mlnikfreak - can you expand on what your scenario is? This issue was specifically about using ActiveX which we won't be doing work to specifically support. However, if you are looking to extend the functionality of Office there are VSTO and JS add-ins you could look into. We also support VB.NET.
**VSTO** - https://docs.microsoft.com/en-us/visualstudio/vsto/office-solutions-development-overview-vsto?view=vs-2019
**Office JS Add-ins** - https://docs.microsoft.com/en-us/office/dev/add-ins/

**Comment by mattmax666** [comment]
hi everyone i also have problem to integrate my webview 2 active X in access/VBA. I create the AciveX in visual studio and in access I have OLE server error when i want to put him in a Access Form.  If you have  any ideas ? Thanks

**Comment by josh-hemphill** [comment]
@champnic Is the `Web Browser Control` in Access an ActiveX control? It's **not** selected from the ActiveX menu, and can currently use the old Edge for rendering.

**Comment by champnic** [comment]
Hey @josh-hemphill - Unfortunately I'm unfamiliar with the `Web Browser Control` in Access. It's probably a WebView(1) if it's using the older EdgeHTML rendering engine.

**Comment by krosoftware** [comment]
Is there any news regarding webview2 as com component? Does somebody created it?

**Comment by sancarn** [comment]
@champnic Yes, `Web Browser Control` used in VBA software is `WebView1`, which is ofc why people are looking for `WebView2` to provide a replacement ActiveX interface.

> because of how outdated Active and Active Containers are as technology, we don't have any plans to support this in the near future

I don't personally think this is a valid statement. ActiveX is indeed an old technology yet hundreds of systems and businesses still rely heavily on the technology. Many businesses still run internally on VBA/Python/Ruby and other scripting languages which often use ActiveX/Win32COM/Win32OLE interface to obtain objects. As a result of implementing such a COM/OLE interface `WebView2` would provide an easy to use Web UI / Web automation framework for Python/Ruby/VBA and numerous other scripting languages which is surely in everyone's interests?
