### ISSUE TITLE
[DMC] Docs seem out of date with new release #819

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebViewFeedback#345]
https://github.com/MicrosoftDocs/edge-developer/issues/819 
Hi, please review the customer reported issue on the documentation. Thanks.

**Comment by LanceMcCarthy** [comment]
Can confirm, please provide either fix to WPF missing type or incorrect xmlns.

**Comment by pagoe-msft** [comment]
@LanceMcCarthy 

Are you getting this error with package 0.9.579-prerelease?

**Comment by LanceMcCarthy** [comment]
No, the issue is with the newer version. This might help clear it up:

![image](https://user-images.githubusercontent.com/3520532/88195401-0133c580-cc0e-11ea-98d9-f34bd7d6486c.png)

Are you saying that the older version tagged with `prerelease1 is actually newer and should be used? the common nomenclature is that the same version number, which does not have prerelease tag, is actually newer.

If that is case, I recommend that you bump the version number for prerelease versions.

**Comment by champnic** [comment]
The versioning is a bit confusing at the moment, because they are tied to the version of the browser they are built against. We actually release them at the same time, so it's not technically "newer". At this point (before we've released GA) both stable and prerelease are built against the Canary channel. Post-GA, the stable version will be built against the Edge Stable channel, and the prerelease package will continue to be built against Canary. Because Edge Stable version is 6 weeks behind Canary, this will result in the prerelease package having a higher version number, which will make more sense and clearer be the newer release.

For now, just think of these packages as being released at the same time, but the prerelease version has extra experimental or preview features, like .NET/WPF support.

**Comment by LanceMcCarthy** [comment]
Thanks @champnic that clears thigns up.

The issue is the way NuGet will list the package in the feed. If a same number is marked with Preview, then it is considered superseded by the non-preview version. a quick note in the Getting Started article will help prevent any future confusion for devs who are adding it manually to projects (as opposed to just cloning the demo)
