### ISSUE TITLE
usage of ICoreWebView2Deferral::Complete() from background thread

### ISSUE THREAD

**Issue by pankajpalOlk** [MicrosoftEdge/WebViewFeedback#376]
Just wanted to understand if ICoreWebView2Deferral::Complete() can be called from a background thread or not. Didn't find any such restrictions being mentioned in the document.

**Comment by pagoe-msft** [comment]
It can't be called from the background thread. The [threading model doc](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model) is intending to say that none of our classes are thread safe unless called out otherwise, I'll look into updating the doc to make it more clear. Thanks for the question!

**Comment by pankajpalOlk** [comment]
Thanks!
