### ISSUE TITLE
webview2 work fine in winformApp,but in office add in, throw nullreferenceException

### ISSUE THREAD

**Issue by yanshuiting** [MicrosoftEdge/WebViewFeedback#404]

**Comment by champnic** [comment]
I reached out to the office folks. It sounds like WebView2-based add-ins are only supported on Win 8.1+. Thanks!

**Comment by yanshuiting** [comment]
I try the vsto  project on another win10（version 17763），get the exception as on the win7.
It seemly the webview2 vsto project only work okay on my Win10（18362） platform！

**Comment by champnic** [comment]
Could you share what the exception stack is on Win10?
Do you have a runtime installed? https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#evergreen-distribution-mode. One of Edge Canary/Dev/Beta, or the WebView2 Runtime preview?

**Comment by champnic** [comment]
@yanshuiting I misspoke earlier. My comment about platform support was referring to Office Web add-ins: https://github.com/OfficeDev/office-js

For VSTO, we're unsure what the level of support is yet, but early testing suggests it should work (and sounds like you have it working on some builds).

**Comment by yanshuiting** [comment]
I try webview2 in Excel-DNA and get the same exception as in vsto. My win10 platform works okay，But another win10 and win7 all get nullreferenceexception.Really confused

**Comment by champnic** [comment]
Do you have answers to my previous questions?

> Could you share what the exception stack is on Win10?
> Do you have a runtime or Edge browser installed? https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#evergreen-distribution-mode. One of Edge Canary/Dev/Beta, or the WebView2 Runtime preview?

**Comment by champnic** [comment]
Actually, can you try this potential fix?
https://github.com/MicrosoftEdge/WebViewFeedback/issues/405#issuecomment-682019097

**Comment by yanshuiting** [comment]
I create a simple VSTO add in,and put the webview2 control to Excel Taskpane, TaskPane control code like below
![image](https://user-images.githubusercontent.com/20025850/91563078-d6f1c800-e970-11ea-929c-a45ce19fd8a8.png)

My Win10 platform  A work okay, and  load the page on the Excel taskpane successfully like below
![image](https://user-images.githubusercontent.com/20025850/91563412-5ed7d200-e971-11ea-9c58-31586fd9900a.png)

But  another win10 platform B and win7 platform all get a clear page like below
![image](https://user-images.githubusercontent.com/20025850/91563649-cdb52b00-e971-11ea-8088-960247651695.png)

The taskpane is clear and get a NullReferenceException
System.NullReferenceException Object reference not set to an instance of an object。
   at Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ActiveXImpl.System.Windows.Forms.IWindowTarget.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Win10 A，Win10 B and win7 all install vs2017 community， Microsoft Edge Canary 86.0.619.0，0.9.538-prerelease.

**Comment by champnic** [comment]
That exception comes from the CoreWebView2Controller failing to properly get created. (We've got a separate workitem tracking fixing the error message to make it more clear) Instead of using the .Source property (which does initialization but loses some error info) can you use web2.EnsureCoreWebViewAsync(..)? Details here: https://github.com/MicrosoftEdge/WebViewFeedback/issues/405#issuecomment-682019097

**Comment by yanshuiting** [comment]
thanks for your advice!

I try the code like #405 ，My Win10 A，woks okay and load page  successfully ,But my Win10 B and win7 still throw 
A access exception，is that security setting problem？

I found the same issue on Developer Community [https://developercommunity.visualstudio.com/content/problem/1100739/webview2-ensurecorewebview2async-systemunauthorize.html](url)

![image](https://user-images.githubusercontent.com/20025850/91633455-f0e7e500-ea1a-11ea-9dc9-e6bf1c6ee0db.png)

the win10 B and Win7 error
![image](https://user-images.githubusercontent.com/20025850/91633520-6784e280-ea1b-11ea-870b-a80759872585.png)

**Comment by champnic** [comment]
The Access Denied exception is because by default WebView2 will create a folder that the browser will use for data, cookies, etc. (the UserDataFolder), at the location of the exe. In the case of an Excel add-in, this default folder is created under C:\Program Files\*, which means the browser won't have write permissions = Access Denied.

To work around this, you need the other parts of the code in https://github.com/MicrosoftEdge/WebViewFeedback/issues/405#issuecomment-682019097, specifically where it sets a different path for the UserDataFolder to be created - a path that the browser can write to successfully. In the sample code, you can see I chose C:\temp.
```        
            // Set the UserDataFolder to something that the runtime can write to.
            var env = await CoreWebView2Environment.CreateAsync(null, "C:\\temp");
            await webView2.EnsureCoreWebView2Async(env);```

**Comment by yanshuiting** [comment]
Thank you champnic and your advice ,
Yes, it does work. Win10 A platform user is the administrator ，That's the reason that it always worked okay.
Many thanks for champnic

**Comment by champnic** [comment]
Awesome, glad it's working!

**Comment by yanshuiting** [comment]
![image](https://user-images.githubusercontent.com/20025850/95083114-a14db500-074e-11eb-96f3-ae45a90cd049.png)

Hi champnic ,I found a confused issue，the code above，if I comment the row **`MessageBox.Show("initialized");`**，I will get error below
![image](https://user-images.githubusercontent.com/20025850/95083523-36e94480-074f-11eb-8cdf-97b8727dd0db.png)

**Comment by yanshuiting** [comment]
I use the web.source，work okay
But，I use web.NavigateToString，get above error, and I muse use  MessageBox.Show() beafore web.NavigateToString,can repaire it

The Code above is in Excel-DNA project

**Comment by champnic** [comment]
This looks related to your usage of async/await. I'm not super familiar with C# async programming, but what's probably happening is that your load function isn't waiting for InitialAsync() to complete before trying to run web.NavigateToString(). It's timing related, which is why MessageBox.Show() allows the initialization to complete before you continue.

There are a few possible fixes:
1. Change InitialAsync() to return the Task from EnsureCoreWebView2Async, and await InitialAsync() in your Plot_Load function.
1. Move the NavigateToString call into the InitialAsync() function after await EnsureCoreWebView2Async.
1. Handle the [CoreWebView2Ready](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/wpf/0-9-515/microsoft-web-webview2-wpf-webview2#corewebview2ready) event and do the NavigateToString in the handler.

Let me know if none of these work for you.
