### ISSUE TITLE
Is there any estimate on the release date of WebView2

### ISSUE THREAD

**Issue by Tibbedoh** [MicrosoftEdge/WebViewFeedback#436]
We use the WebView2 control during development, however we are very reluctant to use it in production, while it is still in preview stage. Are there any estimates on when we will have an official stable release?

**Comment by Symbai** [comment]
I've upvoted because Im interested in the same. But additionally on hearing a date of the first version of the [fixed runtime](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode). The roadmap says Q4 to both. Are you planning near .NET 5 release in November or are you waiting for the current Canary Edge to become stable?

**Comment by Tibbedoh** [comment]
> The roadmap says Q4 to both. 
Do you mind sharing the source of this information? Thanks :D

**Comment by Tibbedoh** [comment]
>  The roadmap says Q4 to both. 

Do you mind sharing the source of this information? Thanks :D

**Comment by champnic** [comment]
Q4 is still the best estimate here. Assuming nothing goes wrong, we're hoping to release the Win32 control and the evergreen WebView2 Runtime in October, and then then Fixed Version Runtimes and .NET controls in November. These aren't hard dates, and are dependent on the quality of the control. Things are looking good so far, but we may hold the release if something unexpected and bad comes up. We release every 6 weeks and will continue to do so, so if anything 'slips', you can probably expect it 6 weeks later.
