### ISSUE TITLE
Instantiating Chromium Edge browser session(Canary) from WebView control 

### ISSUE THREAD

**Issue by santoshmetri** [MicrosoftEdge/WebViewFeedback#47]
I would like to display URL in Chromium Edge browser through WebView. How can I create a session of Chromium edge?

CoCreateInstance() works? if not, how?

Regards,
Santosh

**Comment by david-risney** [comment]
Can you describe your scenario more?

Do you mean that you have an app with a WebView2 control and you have a link you want to open, but you want that link to open in the browser instead of the WebView control? Once opened in the browser, your code in your app has no control over the browser. Is that correct? 

Or is it that you want to open the link in a new window that you still have control over?

If you want to open in the browser I would recommend using the [ShellExecute](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutew) or [LaunchUri](https://docs.microsoft.com/en-us/uwp/api/windows.system.launcher.launchuriasync) OS methods to have the OS start the URI in the user's default browser.

If you want to open a new window that is under your control, you can use [IWebView2WebView3's NewWindowRequested event](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview3#add_newwindowrequested).

Or if I did not understand your request, please explain in greater detail your scenario. Thanks!

**Comment by santoshmetri** [comment]
Hi,

Thank you for the update. Sorry for delayed reply as I was on vacation.


  1.  How can I use ShellExecute or LaunchUri?



Purpose is to display URL in browser session of Microsoft Edge Canary since ShellExecute/LaunchUri is called from WebView.



Does it work if default browser is not “Microsoft Edge Canary”?



  1.  Is it possible to have control by displaying the URL in Microsoft Edge Canary using above mentioned OS methods also?

Regards,
Santosh

**Comment by david-risney** [comment]
The ShellExecute / LaunchUri suggestion is to open the default browser for a URI. You're right that it doesn't let you pick Microsoft Edge it just uses the default browser. If you know the path to the Microsoft Edge executable you could run it, but I don't know of a documented way of obtaining that path.

Internet Explorer had COM objects you could CoCreate and then control telling it to navigate or listen to events etc. The new Microsoft Edge browser does not support that. You might look into [WebDriver ](https://docs.microsoft.com/en-us/microsoft-edge/webdriver) although I don't know what the status of that is for the new Microsoft Edge browser yet.

**Comment by santoshmetri** [comment]
Dear David,

YES, we need a mechanism to display the URLs in Edge Canary browser irrespective of what default browser is in the system.

If the default browser is not Edge canary then the ShellExecute and LaunchUri will not help to display URL in Edge Canary.

Regards,
Santosh

**Comment by champnic** [comment]
This is outside the scope of WebView2, so closing this issue.
You can try the "microsoft-edge://<uri>" protocol - "microsoft-edge://https://bing.com", for example. If that doesn't work, then I suggest you try asking on the Edge forums: https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider

Thanks!
