### ISSUE TITLE
ESM module not working in a UWP/JavaScript or a WebView based XAML app

### ISSUE THREAD

**Issue by mediabuff** [MicrosoftEdge/WebViewFeedback#49]
I am trying to get ESM module working in a UWP/JavaScript or a WebView based XAML app.
Have not been successful so far. I get an activation error, “operation not supported”. Any help would be appreciated.

**Comment by liminzhu** [comment]
Hey @mediabuff , thanks for opening the issue! This repo is actually for the new [WebView2 APIs](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2), but since some of us also own Windows Web Apps (WWA) and XAML WebView with EdgeHTML...

ESM should be able to work in both places, for example, if you have

```js
// index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>WWA1</title>
    <link href="css/default.css" rel="stylesheet" />
</head>
<body>
    <div>Content goes here!</div>
    <script type="module" src="./js/a.js"></script>
    <script type="module" src="./js/b.js"></script>
</body>
</html>

// ./js/a.js
import { f } from "./b.js";
let g = f + 1;
debugger;

// ./js/b.js
export const f = 1;
```

You should see from the breakpoint that ESM is working. You do have to make sure you set the MIME type to `module` in HTML and module specifiers are correct (I ran into `operation not supported` myself when I had the wrong specifier). Also do note that ESM support is added to the JavaScript engine in recent years, so I'd not expect this to work on all versions of Windows 10.

**Comment by mediabuff** [comment]
@liminzhu, thank you. Was able to progress with your code snippet. Now I am trying to see if dynamic imports are supported. That seems to fail.

```
	<script>
		import("./js/a.js");
		import("./js/b.js");
		window.supportsDynamicImport = true;
	</script>
```

**Comment by liminzhu** [comment]
I don't believe EdgeHTML supports dynamic import - https://developer.microsoft.com/en-us/microsoft-edge/platform/status/javascriptmoduleimport/?q=import.

**Comment by mediabuff** [comment]
thank you
