### ISSUE TITLE
Need a way to disable browser context menus and shortcut keys

### ISSUE THREAD

**Issue by wravery** [MicrosoftEdge/WebViewFeedback#57]
I want to blur the lines between native content and HTML content as much as possible in a hybrid app, but keyboard accelerators and context menus seem like they're beyond my control in WebView2. I'd like to be able to shut them off or register callbacks to handle them myself.

If they're shut off, ideally they should each be individually controlled. For instance, I might want to enable `Ctrl+F` to search on the page, but block `Ctrl+S` (Save As) and `Ctrl+P` (Print).

**Comment by pagoe-msft** [comment]
Hi @wravery,

Thanks so much for your feedback! We are aware of demand for both scenarios (keyboard accelerators and context menus) and are working on updating our SDK to give developers control of both. Stay tuned!

**Comment by verelpode** [comment]
Me too!  Yes please!  This is a small but **major** issue in our environment.  We definitely need the ability to disable the built-in context menus and keyboard accelerators/hotkeys because that's a top requirement from our clients.  If end-users are able to display any "Save As" or "Print" window via context menu or keyboard, then our clients will definitely refuse to deploy our software outside of the lab.  A WebView2 that cannot be locked-down or secured is unusable in our environment.

In the case of EdgeHTML-WebView, this issue is already solved -- users can't gain access to "Save As" etc via right-click nor hotkeys.  In the case of the old IE-based WebBrowser Control, the context menu and keyboard accelerators were major problems for us, but we were able to disable them using very ugly hacks.

As @wravery indicated, I agree that if possible, the best solution is to trigger an event when right-click occurs, so that apps can handle right-clicks by themselves, but if that's too difficult, then at least the ability to disable context menus and hotkeys is essential.

**Comment by enricogior** [comment]
Hi,
this is also important for PowerToys. Looking forward for the SDK update that supports this scenario.
Thank you.

**Comment by liminzhu** [comment]
Happy to report that we just shipped accelerator key event and the ability to disable context menu in [0.8.314](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes#08314). Closing the issue for now and feel free to re-open and issue and let us know if you have additional feedback.

**Comment by enricogior** [comment]
@liminzhu thank you!
