### ISSUE TITLE
Can't type on popup dialog

### ISSUE THREAD

**Issue by Pirrang** [MicrosoftEdge/WebViewFeedback#64]
Hi, I'm trying to access to remote server though the webview2. While getting access to it it's normal to be asked credentials. However, it seems like I can't type anything in the username and password textfield. I can only click on sign-in  and cancel button. Is there a way to unlock this ?

Edit: this pop-up dialog is not coming from custom dialog. It's an automatic dialog from Edge

![sign-in](https://user-images.githubusercontent.com/45078653/67455832-194ec800-f62f-11e9-9a12-ed8da9496db7.png)

**Comment by david-risney** [comment]
Thanks for trying WebView2 and the great bug report! We'll look into this issue and get back to you.

**Comment by verelpode** [comment]
I'd forgotten about that HTTP authorization modal dialog, so I'm glad you took the time to report it, because this dialog has also been a long-running issue for us or our customers.  The real underlying difficulty is that even if the WebView2 team fixes this bug by restoring the ability of users to type in the textboxes, this dialog still won't be truly fixed.  It'll still find _some_ way of malfunctioning or causing trouble as these dialogs always have.  For example, something like one of the following will occur:

* Incompatible with all or some touchscreens, such as perhaps wall-mounted touchscreens; or
* Theoretically compatible with touchscreens but unusable in practice because no onscreen-keyboard appears when the user tries to enter text in the textboxes, or the buttons are too small to operate in practice with some touchscreens.
* WebView2 displays a dialog intended to behave as a modal dialog but the modality behavior is dysfunctional because WebView2 runs in a separate process than the host app.
* The DPI, scaling, or otherwise just simply the default chosen font size is too small and users are unable to read it when it appears on certain types of screens or when the users are located some distance away from the screen and cannot come closer, and no way exists to change the font size.
* The appearance/theme of the dialog is wrong in the sense that it doesn't match the rest of the system or host app.  This is compounded by the fact that the WebView2 component is implemented in Win32 whereas the host app will often be a UWP app and this can lead to mismatching appearances and/or behaviors between Win32 versus UWP.
* The language of the text in the dialog is the wrong language and no way exists to fix it.
* End-users find the text/explanation in the dialog confusing or ambiguous and no way exists to change the text.
* Microsoft thinks the dialog is easily understood by users but in reality too many users don't understand it or don't have time to learn it or deal with it.
* The dialog frightens or worries users and causes them to contact tech support or just stop using the computer.  For example, the screenshot in the first message says "not secure".
* The dialog has a problematic side-effect of permanently changing settings in the OS.
* The dialog automatically remembers/recalls sensitive info and it is difficult or impossible to make it erase this sensitive info.
* When the dialog is displayed, perhaps located at the top of the screen instead of the middle, users report that the web browser is broken because clicking in the webpage does nothing because they don't know that the dialog causes the webpage to ignore clicks until the dialog is dismissed, and the dialog didn't cause any dimming of the rest of the screen, or the dialog is otherwise insufficiently conspicuous.
* The software crashes or otherwise malfunctions when something happens via multitasking or networking while the modal dialog is displayed, such as something along the lines of trying to terminate/dispose or reset a WebView2 instance (or change its settings or invoke some method in WebView2) at a time while WebView2 is displaying the modal dialog.  Or otherwise needing to programmatically operate or cancel the dialog and being unable to do so.
* And many other problems that do exist but that I can't immediately remember right now.

Fundamentally, this authorization dialog problem is yet another example of what I mentioned in [issue #59](https://github.com/MicrosoftEdge/WebViewFeedback/issues/59):

> In my experience with WebView and the older WebBrowser, any dialogs and extra windows displayed by WebView end up causing trouble. Not only do they cause trouble, they're also unnecessary because any necessary dialogs can be displayed by the app instead of WebView.

I hope that the WebView2 team can sympathize and understand how very frustrating the situation is for me, because I've had to deal with this problem again and again and AGAIN over the course of YEARS, and just when I think I've finally reached the end of it, a customer reports to me yet another form or variation of the same problem.  I test it and see that the customer is correct, and then I must struggle with the difficulty of finding a way to somehow prevent the web component from displaying yet another problematic window or pseudo-window (including dialogs, windows, popups, context menus, toolbars).  When will it end?!   

Please please please consider making it possible to configure WebView2 in a way that allows the app to suppress, override, or replace EVERY single kind of extra dialog, window, pseudo-window, popup, menu, toolbar, etc.  Every one of them eventually causes trouble in one way or another!  I've been dealing with this for years.

@david-risney wrote:
> By default as a baseline WebView2 acts similar to the browser so the end developer doesn't have to understand and use every feature of WebView2 in order to have a working WebView2. Without reading about every feature the end developer can assume ….

That concept is very nice to end developers and it's appreciated, but unfortunately it just doesn't work in practice, so I think the concept needs to be modified.

What you described is a nice wish, and I wish for it too, but unfortunately it's no more than a wish.  When WebView2 is a WinUI or WPF Control, and when WebView2 displays its own dialogs, it's not just possible to make WebView2 operate reliably, bug-free, trouble-free.   The end of the problems will never be reached when that path is followed.

**Comment by Pirrang** [comment]
Thanks @verelpode  for you detailed answer I didn't know it could create so much trouble. I'll check how can I do those suppression of extra dialog. Actually, this modal dialog is not something I tend to have in the end.

**Comment by david-risney** [comment]
Hi @Pirrang, I believe @verelpode is talking about their issue #59 not the bug you reported and is asking for a WebView2 feature to disable the auth dialog. We are looking into the bug you found and let you know how its going. Thanks!

**Comment by champnic** [comment]
Fix available in 80.0.339.0+
