### ISSUE TITLE
WebView 2 and WebView(EdgeHTML)

### ISSUE THREAD

**Issue by Dmitiry-hub** [MicrosoftEdge/WebViewFeedback#71]
I have a couple of questions related to WebView for WPF C# .NET.
1. Will EdgeHTML WebView support be discontinued?
2. Can I remake my project from WebView (EdgeHTML) to WebView? 
How hard is that going to be?

3.How different will WebView (EdgeHTML) and WebView 2 be?
4.When will WebView 2 be released for .NET C# WPF and WinForms?

**Comment by david-risney** [comment]
Great questions!
1. We currently have no plans to deprecate or discontinue EdgeHtml based WebViews or WwaHost. However, other than security fixes Microsoft is no longer investing in EdgeHtml.
2. There are some differences in some of the APIs. Generally it won't be too difficult to move from EdgeHtml based WebView to WebView2. We'll have a document in the future to inform how to transition.
3. The main differences stem from:
   1. Underlying browser is now Chromium based. No Microsoft specific DOM APIs etc. Associated web compat improvements.
   2. WebView2 is built on the whole browser rather than EdgeHtml WebView building on top of a lower portion of the browser. This means we get by default the browser's security model and process model. We are starting with out-of-proc matching the browser and investigating in-proc options in the future unlike EdgeHtml WebView which started with in proc and then had to re-implement a simpler version of out-of-proc like in EdgeHtml WebView.
   3. WebView2 is built on the new Microsoft Edge which is Win32 first. We're working on UWP support.
4. We're currently working on .NET support and it should be available in the first half of next year with a dev preview sometime earlier than that.
