### ISSUE TITLE
Synchronous Calls from JavaScript to C++

### ISSUE THREAD

**Issue by my2iu** [MicrosoftEdge/WebViewFeedback#90]
I know the sandbox makes  things difficult, but it's always nice to be able to make a synchronous call from JavaScript into C++. It would be great to also support synchronous C++ to JavaScript calls, but I don't think that would work well with the JavaScript language model. 

Ideally, synchronous calls from JavaScript to C++ would be a low overhead call, but if you have to block the entire process and wait on some IPC thing while C++ does its thing, that's fine too. Sometimes, I just need to do something synchronously, and I think it should be left to developers' experience to decide when it's appropriate or not and not force some asynchronous model on me. I believe the Android WebView supports this, and it just makes things a whole lot easier than the Apple WebView. You can do all sorts of native integrations much more cleanly and much more easily.

**Comment by nmoinvaz** [comment]
I think this is possible to do Javascript to C++ via IDispatch, same method as in Trident.

**Comment by my2iu** [comment]
That’s great. In that case, I guess the WebView2 documentation should be updated to mention that. There’s no way anyone has the time to dig into that old Trident stuff to see what’s there.

**Comment by nmoinvaz** [comment]
See #17. https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview4#addremoteobject

**Comment by my2iu** [comment]
Great. Do these callbacks happen on the UI thread or on some other thread? I previously encountered problems with the iOS WebView because the OS required some things to happen in a callback in the UI thread, but I couldn’t get any data out of JavaScript because all the event handlers were also handled in the UI thread, but I would have to exit the callback in was currently for that code to execute.

Longer term, it would also be good to have a low overhead synchronous call. Maybe there could be a way to tell the WebView to load a .dll into the sandbox where it could be called synchronously from JavaScript with low overhead.

**Comment by david-risney** [comment]
Yes, at the moment we only support interacting with the WebView on the UI thread on which it is created ([docs](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#threading-model)). I'll open a separate feature request issue for supporting callbacks or otherwise interacting with the WebView from other threads.

Just letting you load a dll into the sandbox isn't generally useful because the sandbox is so locked down and its also a future compat issue waiting to happen since its always getting more locked down. Folks who want to synchronously call native code from their JavaScript so far have also wanted a different process model / security model so that their code can run correctly. I'll open a separate feature request for that.

**Comment by my2iu** [comment]
I think it would be a good idea to mention the existence of this callback mechanism in the Getting Started docs, but I’m satisfied with the API, so if you want to close this issue, go ahead.
