### ISSUE TITLE
App in development working with Dev and Can builds but not Beta

### ISSUE THREAD

**Issue by douglas-jordan** [MicrosoftEdge/WebViewFeedback#96]
I am using VS2019 and WebView2 SDK 0.8.355.  I don't have anything coded for a specific version.

Code works with Dev and Can builds but not with the Beta.  Tested on Windows 7 and Windows 10.  In anticipation of the release next week I wanted to test with the Beta build and uninstalled the dev build from my Windows 10 test system.  The browser works from the desktop icon but my app does not.  Uninstall beta build and install the dev build and it is working again.

The beta version is greater than the minimum version required version of 78.0.270.0.  Does the most current SDK 0.8.355 require a later version than 79.x?

Any thoughts as to what the issue might be?

**Comment by TcT2k** [comment]
In the [release notes](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes#08355) you can see that the current minimum version is 80.0.355.0
I've also tried with the beta, but that doesn't seem new enough currently.

**Comment by douglas-jordan** [comment]
> In the [release notes](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes#08355) you can see that the current minimum version is 80.0.355.0
> I've also tried with the beta, but that doesn't seem new enough currently.

Thanks for the link and the tip.

**Comment by pagoe-msft** [comment]
Hi douglas-jordan,

Is your issue resolved?

**Comment by douglas-jordan** [comment]
> Hi douglas-jordan,
> 
> Is your issue resolved?

Yes.  Please post if you know what the release version will be next week.  I have customers waiting on my update which includes support for MS-EDGE-CHROMIUM and it is doubtful they will use a non-release version.  Thanks.

**Comment by liminzhu** [comment]
> next week

I'm pleasantly surprised you're following our 6-week release cadence :D. Unfortunately though, we want to get most of our breaking changes before V1 in our next release (we like to do breaking changes in big patches so that we don't break developers as often) and that will delays our next release for a couple.

In terms of the browser, it will be whatever the Canary build is near our ship date, so I'd expect 81. Within our preview phase, we're requiring the minimum to match Canary so that we can be very agile and give developers new APIs as soon as they become available. When we reach WebView2 V1 release, we will align with Stable browser as we're aware developers cannot require their end users to have Canary.

**Comment by douglas-jordan** [comment]
Appears build 79 is the release version that is available today.  So we have to wait for that to catch up to a later build.

**Comment by liminzhu** [comment]
Right, the current Stable build on my box is 79.0.309.65. [WebView 0.8.270](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes#08270) should be working if you don't need some of the latest APIs.

**Comment by douglas-jordan** [comment]
For all interested the release version updated to 80.0.361.48 today and works with the 0.8.355 SDK.
